#version 430

layout(local_size_x = 256) in;

layout(std430, binding = 5) readonly buffer CellCountBuffer { uint cellCounts[]; };
layout(std430, binding = 6) writeonly buffer CellOffsetBuffer { uint cellOffsets[]; };
layout(std430, binding = 8) writeonly buffer BlockSumBuffer { uint blockSums[]; };

uniform uint uCellCount;
shared uint scratch[256];

void main()
{
	uint local_index = gl_LocalInvocationID.x;
	uint global_index = gl_GlobalInvocationID.x;
	uint value = global_index < uCellCount ? cellCounts[global_index] : 0u;
	scratch[local_index] = value;
	barrier();
	for (uint offset = 1u; offset < 256u; offset <<= 1u) {
		uint addend = local_index >= offset ? scratch[local_index - offset] : 0u;
		barrier();
		scratch[local_index] += addend;
		barrier();
	}
	if (global_index < uCellCount)
		cellOffsets[global_index] = scratch[local_index] - value;
	uint first = gl_WorkGroupID.x * 256u;
	uint valid_count = min(256u, uCellCount - first);
	if (local_index + 1u == valid_count)
		blockSums[gl_WorkGroupID.x] = scratch[local_index];
}
